// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFriendGroup = "friend_groups"

// FriendGroup mapped from table <friend_groups>
type FriendGroup struct {
	UserID    int64  `gorm:"column:user_id;primaryKey" json:"user_id"`       // 用户id
	GroupName string `gorm:"column:group_name;primaryKey" json:"group_name"` // 好友分组名称
}

// TableName FriendGroup's table name
func (*FriendGroup) TableName() string {
	return TableNameFriendGroup
}
