server:
  grpc:
    addr: x.x.x.x:port #开放端口
    timeout: 1s
    endpoint: x.x.x.x:port #一定要是公网ip
  name: logic_user
  version: "1.0"
  environment: "dev"
config:
  group: "pangchat"
  data_id: "logic_user.yaml"
nacos:
  addrs:
    - x.x.x.x:port #nacos开放端口
#下面为在配置中心的配置，不需要可以注释掉
#service:
#  user_service: logic_user
#  relationship_service: logic_relationship
#discovery:
#  etcd:
#    addrs:
#      - x.x.x.x:port #etcd开放端口
#registry:
#  etcd:
#    addrs:
#      - x.x.x.x:port #etcd开放端口
#snowflake:
#  worker_id: 1
#data:
#  database:
#    driver: mysql
#    source: xxx:xxx@tcp(x.x.x.x:port)/xxx #数据库
#  redis:
#    addr: x.x.x.x:port #redis开放端口
#    password: xxx
#    db: 0
#    pool_size: 100
#    min_idle_conns: 10
#    max_retries: 3
#    read_timeout: 0.2s
#    write_timeout: 0.2s
#aliyun:
#  access_key: xxx
#  access_secret: xxx
#  sms:
#    sign_name: xxx
#    template_code: xxx
#    region_id: xxx
#    endpoint: xxx
#  oss:
#    endpoint: xxx
#    bucket: xxx
#  sts:
#    endpoint: xxx
#    role_arn: xxx
#    role_session_name: xxx