// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-gateway/internal/components/auth"
	"api-gateway/internal/components/client"
	"api-gateway/internal/components/logger"
	"api-gateway/internal/components/registry"
	"api-gateway/internal/conf"
	"api-gateway/internal/server"
	"api-gateway/internal/service/connector"
	"api-gateway/internal/service/logic"
	"api-gateway/internal/service/message"
	"api-gateway/internal/service/online"
	"api-gateway/internal/service/relationship"
	"api-gateway/internal/service/user"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logLogger log.Logger) (*kratos.App, func(), error) {
	helper := logger.NewHelper(logLogger)
	jwtManager := auth.NewJwtManager(bootstrap)
	clientv3Client, err := registry.NewEtcdClient(bootstrap, helper)
	if err != nil {
		return nil, nil, err
	}
	messageRegistry := registry.NewMessageRegistry(bootstrap, clientv3Client)
	messageServiceClient, err := client.NewMessageClient(messageRegistry, helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	message := service_message.NewMessage(helper, jwtManager, messageServiceClient)
	userRegistry := registry.NewEtcdUserRegistry(bootstrap, clientv3Client)
	userClient, err := client.NewUserClient(userRegistry, helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	userService := service_user.NewUserService(userClient, helper, jwtManager)
	connectorRegistry := registry.NewEtcdConnectorRegistry(bootstrap, clientv3Client)
	connectorServiceClient, err := client.NewConnectorClient(connectorRegistry, helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	connectorService := service_connector.NewConnectorService(connectorServiceClient, helper, jwtManager)
	logicRegistry := registry.NewEtcdLogicRegistry(bootstrap, clientv3Client)
	logicClient, err := client.NewLogicClient(logicRegistry, helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	logicService := service_logic.NewLogicService(logicClient, helper, jwtManager)
	relationshipRegistry := registry.NewEtcdRelationshipRegistry(bootstrap, clientv3Client)
	relationShipClient, err := client.NewRelationshipClient(relationshipRegistry, helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	relationship := service_relationship.NewRelationship(helper, relationShipClient, jwtManager)
	onlineRegistry := registry.NewOnlineRegistry(bootstrap, clientv3Client)
	onlineClient, err := client.NewOnlineClient(onlineRegistry, helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	online := service_online.NewOnline(helper, jwtManager, onlineClient)
	httpServer := server.NewHTTPServer(bootstrap, message, userService, connectorService, logicService, relationship, online)
	app := newApp(logLogger, httpServer)
	return app, func() {
	}, nil
}
