server:
  http:
    addr: 0.0.0.0:8081
    timeout: 1s
  name: "api_gateway"
service:
  user_service: "logic_user"
  connector_service: "connector"
  logic_service: "logic_logic"
  relationship_service: "logic_relationship"
  online_service: "online"
  message_service: "logic_message"
discovery:
  etcd:
    addrs:
      - 43.143.137.232:2379
registry:
  etcd:
    addrs:
      - 43.143.137.232:2379
jwt:
  key: "mysecret"