server:
  http:
    addr: x.x.x.x:port #开放端口
    timeout: 1s
  name: "api_gateway"
service:
  user_service: "logic_user"
  connector_service: "connector"
  logic_service: "logic_logic"
  relationship_service: "logic_relationship"
  online_service: "online"
  message_service: "logic_message"
discovery:
  etcd:
    addrs:
      - x.x.x.x:port #etcd地址
registry:
  etcd:
    addrs:
      - x.x.x.x:port #etcd地址
jwt:
  key: "自定义密钥"