// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"connector/internal/data/orm/model"
)

func newProvince(db *gorm.DB, opts ...gen.DOOption) province {
	_province := province{}

	_province.provinceDo.UseDB(db, opts...)
	_province.provinceDo.UseModel(&model.Province{})

	tableName := _province.provinceDo.TableName()
	_province.ALL = field.NewAsterisk(tableName)
	_province.ProvinceID = field.NewString(tableName, "province_id")
	_province.ProvinceName = field.NewString(tableName, "province_name")

	_province.fillFieldMap()

	return _province
}

type province struct {
	provinceDo provinceDo

	ALL          field.Asterisk
	ProvinceID   field.String // 省份id
	ProvinceName field.String // 省份名称

	fieldMap map[string]field.Expr
}

func (p province) Table(newTableName string) *province {
	p.provinceDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p province) As(alias string) *province {
	p.provinceDo.DO = *(p.provinceDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *province) updateTableName(table string) *province {
	p.ALL = field.NewAsterisk(table)
	p.ProvinceID = field.NewString(table, "province_id")
	p.ProvinceName = field.NewString(table, "province_name")

	p.fillFieldMap()

	return p
}

func (p *province) WithContext(ctx context.Context) *provinceDo { return p.provinceDo.WithContext(ctx) }

func (p province) TableName() string { return p.provinceDo.TableName() }

func (p province) Alias() string { return p.provinceDo.Alias() }

func (p *province) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *province) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["province_id"] = p.ProvinceID
	p.fieldMap["province_name"] = p.ProvinceName
}

func (p province) clone(db *gorm.DB) province {
	p.provinceDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p province) replaceDB(db *gorm.DB) province {
	p.provinceDo.ReplaceDB(db)
	return p
}

type provinceDo struct{ gen.DO }

func (p provinceDo) Debug() *provinceDo {
	return p.withDO(p.DO.Debug())
}

func (p provinceDo) WithContext(ctx context.Context) *provinceDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p provinceDo) ReadDB() *provinceDo {
	return p.Clauses(dbresolver.Read)
}

func (p provinceDo) WriteDB() *provinceDo {
	return p.Clauses(dbresolver.Write)
}

func (p provinceDo) Session(config *gorm.Session) *provinceDo {
	return p.withDO(p.DO.Session(config))
}

func (p provinceDo) Clauses(conds ...clause.Expression) *provinceDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p provinceDo) Returning(value interface{}, columns ...string) *provinceDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p provinceDo) Not(conds ...gen.Condition) *provinceDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p provinceDo) Or(conds ...gen.Condition) *provinceDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p provinceDo) Select(conds ...field.Expr) *provinceDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p provinceDo) Where(conds ...gen.Condition) *provinceDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p provinceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *provinceDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p provinceDo) Order(conds ...field.Expr) *provinceDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p provinceDo) Distinct(cols ...field.Expr) *provinceDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p provinceDo) Omit(cols ...field.Expr) *provinceDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p provinceDo) Join(table schema.Tabler, on ...field.Expr) *provinceDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p provinceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *provinceDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p provinceDo) RightJoin(table schema.Tabler, on ...field.Expr) *provinceDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p provinceDo) Group(cols ...field.Expr) *provinceDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p provinceDo) Having(conds ...gen.Condition) *provinceDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p provinceDo) Limit(limit int) *provinceDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p provinceDo) Offset(offset int) *provinceDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p provinceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *provinceDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p provinceDo) Unscoped() *provinceDo {
	return p.withDO(p.DO.Unscoped())
}

func (p provinceDo) Create(values ...*model.Province) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p provinceDo) CreateInBatches(values []*model.Province, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p provinceDo) Save(values ...*model.Province) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p provinceDo) First() (*model.Province, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Province), nil
	}
}

func (p provinceDo) Take() (*model.Province, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Province), nil
	}
}

func (p provinceDo) Last() (*model.Province, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Province), nil
	}
}

func (p provinceDo) Find() ([]*model.Province, error) {
	result, err := p.DO.Find()
	return result.([]*model.Province), err
}

func (p provinceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Province, err error) {
	buf := make([]*model.Province, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p provinceDo) FindInBatches(result *[]*model.Province, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p provinceDo) Attrs(attrs ...field.AssignExpr) *provinceDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p provinceDo) Assign(attrs ...field.AssignExpr) *provinceDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p provinceDo) Joins(fields ...field.RelationField) *provinceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p provinceDo) Preload(fields ...field.RelationField) *provinceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p provinceDo) FirstOrInit() (*model.Province, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Province), nil
	}
}

func (p provinceDo) FirstOrCreate() (*model.Province, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Province), nil
	}
}

func (p provinceDo) FindByPage(offset int, limit int) (result []*model.Province, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p provinceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p provinceDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p provinceDo) Delete(models ...*model.Province) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *provinceDo) withDO(do gen.Dao) *provinceDo {
	p.DO = *do.(*gen.DO)
	return p
}
