genUser:
	go run main.go -service logic.user
genMessage:
	go run main.go -service history-message
genGroup:
	go run main.go -service group
genConnector:
	go run main.go -service connector
genRelationship:
	go run main.go -service logic.relationship
genLogic:
	go run main.go -service logic.logic
genMessage:
	go run main.go -service logic.message
.PHONY: genUser genMessage genGroup