server:
  grpc:
    addr: 0.0.0.0:9008
    timeout: 1s
  name: logic_logic
  version: "1.0"
  environment: "dev"
service:
  logic_service: logic_logic
  connector_service: connector
discovery:
  etcd:
    addrs:
      - 127.0.0.1:2379
registry:
  etcd:
    addrs:
      - 127.0.0.1:2379
data:
  redis:
    addr: 127.0.0.1:6379
    password: password
    db: 0
    pool_size: 100
    min_idle_conns: 10
    max_retries: 3
    read_timeout: 0.2s
    write_timeout: 0.2s