// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: v1/logic.proto

package logic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConnectorUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConnectorUrlRequest) Reset() {
	*x = GetConnectorUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectorUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorUrlRequest) ProtoMessage() {}

func (x *GetConnectorUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorUrlRequest.ProtoReflect.Descriptor instead.
func (*GetConnectorUrlRequest) Descriptor() ([]byte, []int) {
	return file_v1_logic_proto_rawDescGZIP(), []int{0}
}

type GetConnectorUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *GetConnectorUrlResponse) Reset() {
	*x = GetConnectorUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectorUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorUrlResponse) ProtoMessage() {}

func (x *GetConnectorUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorUrlResponse.ProtoReflect.Descriptor instead.
func (*GetConnectorUrlResponse) Descriptor() ([]byte, []int) {
	return file_v1_logic_proto_rawDescGZIP(), []int{1}
}

func (x *GetConnectorUrlResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetConnectorUrlResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

var File_v1_logic_proto protoreflect.FileDescriptor

var file_v1_logic_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x32, 0x73, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x6a, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x2a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x3b, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_logic_proto_rawDescOnce sync.Once
	file_v1_logic_proto_rawDescData = file_v1_logic_proto_rawDesc
)

func file_v1_logic_proto_rawDescGZIP() []byte {
	file_v1_logic_proto_rawDescOnce.Do(func() {
		file_v1_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_logic_proto_rawDescData)
	})
	return file_v1_logic_proto_rawDescData
}

var file_v1_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_logic_proto_goTypes = []interface{}{
	(*GetConnectorUrlRequest)(nil),  // 0: api.v1.logic.logic.GetConnectorUrlRequest
	(*GetConnectorUrlResponse)(nil), // 1: api.v1.logic.logic.GetConnectorUrlResponse
}
var file_v1_logic_proto_depIdxs = []int32{
	0, // 0: api.v1.logic.logic.Logic.GetConnectorUrl:input_type -> api.v1.logic.logic.GetConnectorUrlRequest
	1, // 1: api.v1.logic.logic.Logic.GetConnectorUrl:output_type -> api.v1.logic.logic.GetConnectorUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_logic_proto_init() }
func file_v1_logic_proto_init() {
	if File_v1_logic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectorUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectorUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_logic_proto_goTypes,
		DependencyIndexes: file_v1_logic_proto_depIdxs,
		MessageInfos:      file_v1_logic_proto_msgTypes,
	}.Build()
	File_v1_logic_proto = out.File
	file_v1_logic_proto_rawDesc = nil
	file_v1_logic_proto_goTypes = nil
	file_v1_logic_proto_depIdxs = nil
}
