server:
  http:
    addr: 0.0.0.0:8002
    endpoint: 192.168.37.1:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    endpoint: 192.168.37.1:9003
    timeout: 1s
  name: connector
  version: "1.0"
  environment: "dev"
service:
  connector_service: connector
  user_service: logic_user
  relationship_service: logic_relationship
  online_service: online
  message_service: logic_message
kafka:
  addrs:
    - 43.143.137.232:9092
message_queue:
  friend_request_topic: friend_request
  friend_request_group: friend_request_group
  connect_topic: connect
  connect_group: connect_group
discovery:
  etcd:
    addrs:
      - 43.143.137.232:2379
registry:
  etcd:
    addrs:
      - 43.143.137.232:2379
data:
  database:
    driver: mysql
    source: pangchat:password@tcp(43.143.137.232:3307)/pangchat
  redis:
    addr: 43.143.137.232:6379
    password: password
    db: 0
    pool_size: 100
    min_idle_conns: 10
    max_retries: 3
    read_timeout: 0.4s
    write_timeout: 0.6s