run:
	cd ./logic/user && kratos run&
	cd ./logic/logic && kratos run&
	cd ./logic/relationship && kratos run&
	cd ./connector && kratos run&
	cd ./online && kratos run&
	cd ./job && kratos run&
	cd ./api-gateway && kratos run&